#print("my name is mitchell")
#print("my surname is king")
#print("my gender is female")
#print("i am 25 years old")
#print("i am from kogi state")
#print("i am a doctor")

name = input("enter your name: ")
surname = input("enter your surname: ")
gender = input("sex: ")
age = input("how old are you: ")
state = input("state of origin: ")
occupation = input("what is your occupation: ")
print("my name is",name)
print("my surname is",surname)
print("my gender is",gender)
print("i am",age,"years old")
print("i am from",state,"state")
print("i am a",occupation)